import { StyleSheet, Platform } from 'react-native';
import { ThemeColors } from '../../context/ThemeContext';
export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    // ── Header ────────────────────────────────────────────────
    header: {
      paddingTop: Platform.OS === 'ios' ? 58 : 42,
      paddingBottom: 16,
      paddingHorizontal: 18,
      backgroundColor: colors.headerBg,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    backBtn: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 4,
      elevation: 2,
    },
    headerCenter: {
      flex: 1,
      alignItems: 'center',
      paddingHorizontal: 12,
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: colors.text,
      letterSpacing: -0.5,
    },
    headerSub: {
      fontSize: 11,
      color: colors.textMuted,
      marginTop: 2,
      letterSpacing: 0.2,
    },
    // ── Bottom save bar ───────────────────────────────────────
    bottomBar: {
      paddingHorizontal: 18,
      paddingTop: 12,
      paddingBottom: Platform.OS === 'ios' ? 36 : 20,
      backgroundColor: colors.headerBg,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    saveBtn: {
      backgroundColor: colors.accent,
      paddingVertical: 16,
      borderRadius: 50,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 8,
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.35,
      shadowRadius: 10,
      elevation: 5,
    },
    saveBtnDisabled: { opacity: 0.45, shadowOpacity: 0 },
    saveBtnText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '800',
      letterSpacing: 0.2,
    },
    // ── Scroll ────────────────────────────────────────────────
    scroll: { flex: 1 },
    scrollContent: { paddingBottom: 24 },
    // ── Info bar ──────────────────────────────────────────────
    infoBar: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      marginHorizontal: 18,
      marginTop: 18,
      marginBottom: 4,
      paddingHorizontal: 14,
      paddingVertical: 12,
      backgroundColor: colors.accentDim,
      borderRadius: 14,
      borderLeftWidth: 3,
      borderLeftColor: colors.accent,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.accent + '30',
    },
    infoBarText: {
      flex: 1,
      fontSize: 12,
      color: colors.accent,
      fontWeight: '500',
      lineHeight: 18,
    },
    // ── Form section ──────────────────────────────────────────
    formSection: {
      marginHorizontal: 18,
      marginTop: 18,
      gap: 16,
    },
    // ── Field card — shared by Photo, Title, Description ──────
    fieldCard: {
      backgroundColor: colors.surface,
      borderRadius: 18,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 3,
    },
    fieldCardFocused: {
      borderColor: colors.accent,
      borderWidth: 1.5,
      shadowColor: colors.accent,
      shadowOpacity: 0.12,
      shadowRadius: 10,
    },
    fieldCardError: {
      borderColor: colors.danger,
      borderWidth: 1.5,
      shadowColor: colors.danger,
      shadowOpacity: 0.1,
      shadowRadius: 8,
    },
    // ── Field header row ──────────────────────────────────────
    fieldHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 2,
    },
    fieldLabelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
    },
    fieldIconWrap: {
      width: 28,
      height: 28,
      borderRadius: 8,
      backgroundColor: colors.accentDim,
      alignItems: 'center',
      justifyContent: 'center',
    },
    fieldLabel: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.text,
      letterSpacing: -0.2,
    },
    fieldBadge: {
      fontSize: 10,
      fontWeight: '700',
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 6,
      overflow: 'hidden',
    },
    fieldBadgeRequired: {
      color: colors.danger,
      backgroundColor: colors.dangerDim,
    },
    fieldBadgeOptional: {
      color: colors.textMuted,
      backgroundColor: colors.surfaceElevated,
    },
    fieldBadgeLocked: {
      color: colors.textMuted,
      backgroundColor: colors.surfaceElevated,
    },
    fieldHint: {
      fontSize: 12,
      color: colors.textMuted,
      marginBottom: 12,
      lineHeight: 17,
      marginTop: 4,
    },
    // ── Camera inner container ────────────────────────────────
    cameraInner: {
      borderRadius: 12,
      overflow: 'hidden',
      backgroundColor: colors.surfaceElevated,
    },
    cameraInnerError: {},
    photoPlaceholder: {
      height: 190,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingHorizontal: 32,
    },
    photoPlaceholderIconCircle: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: colors.accentDim,
      borderWidth: 1.5,
      borderColor: colors.accent + '40',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 4,
    },
    photoPlaceholderTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
      letterSpacing: -0.3,
    },
    photoPlaceholderSub: {
      fontSize: 12,
      color: colors.textSecondary,
      textAlign: 'center',
      lineHeight: 17,
    },
    openCameraBtn: {
      marginTop: 10,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      backgroundColor: colors.accent,
      paddingHorizontal: 24,
      paddingVertical: 11,
      borderRadius: 50,
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      elevation: 4,
    },
    openCameraBtnText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: '700',
    },
    photoPreview: {
      width: '100%',
      height: 190,
    },
    photoOverlayRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 9,
      backgroundColor: 'rgba(0,0,0,0.55)',
    },
    addressRow: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      marginRight: 8,
    },
    addressText: {
      flex: 1,
      fontSize: 11,
      color: '#FFFFFF',
      fontWeight: '600',
    },
    addressLoading: {
      flex: 1,
      fontSize: 11,
      color: 'rgba(255,255,255,0.75)',
      fontStyle: 'italic',
    },
    retakeBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      backgroundColor: 'rgba(255,255,255,0.2)',
      paddingHorizontal: 11,
      paddingVertical: 6,
      borderRadius: 50,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.35)',
    },
    retakeBtnText: {
      color: '#FFFFFF',
      fontSize: 11,
      fontWeight: '700',
    },
    photoErrorText: {
      fontSize: 12,
      color: colors.danger,
      marginTop: 8,
    },
    // Edit screen — readonly badge below photo
    readonlyBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 5,
      paddingVertical: 8,
      marginTop: 10,
      backgroundColor: colors.surfaceElevated,
      borderRadius: 8,
    },
    readonlyText: {
      fontSize: 11,
      color: colors.textMuted,
      fontWeight: '500',
    },
    // ── Text inputs ───────────────────────────────────────────
    input: {
      fontSize: 15,
      color: colors.text,
      paddingVertical: 12,
      paddingHorizontal: 14,
      minHeight: 48,
      backgroundColor: colors.surfaceElevated,
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    inputFocused: {
      borderColor: colors.accent,
      borderWidth: 1,
      backgroundColor: colors.accentDim,
    },
    textArea: {
      height: 110,
      textAlignVertical: 'top',
      paddingTop: 12,
    },
    fieldFooter: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 8,
    },
    fieldError: {
      fontSize: 11,
      color: colors.danger,
      flex: 1,
    },
    charCount: {
      fontSize: 11,
      color: colors.textMuted,
      fontWeight: '500',
    },
    charCountWarn: { color: colors.danger },
  });