import { StyleSheet, Platform } from 'react-native';
import { ThemeColors } from '../../context/ThemeContext';

export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      paddingTop: Platform.OS === 'ios' ? 56 : 40,
      paddingBottom: 14,
      paddingHorizontal: 18,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.headerBg,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    backBtn: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: colors.surfaceElevated,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    backBtnText: {
      color: colors.text,
      fontSize: 18,
    },
    headerCenter: {
      flex: 1,
      alignItems: 'center',
      paddingHorizontal: 10,
    },
    headerTitle: {
      fontSize: 17,
      fontWeight: '800',
      color: colors.text,
      letterSpacing: -0.3,
    },
    headerSubtitle: {
      fontSize: 11,
      color: colors.textSecondary,
      marginTop: 2,
    },
    saveBtn: {
      backgroundColor: colors.accent,
      paddingHorizontal: 18,
      paddingVertical: 8,
      borderRadius: 50,
      minWidth: 72,
      alignItems: 'center',
      justifyContent: 'center',
    },
    saveBtnDisabled: {
      opacity: 0.5,
    },
    saveBtnText: {
      color: colors.white,
      fontSize: 14,
      fontWeight: '800',
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      paddingBottom: 80,
    },
    photoSection: {
      margin: 14,
      borderRadius: 18,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: colors.border,
    },
    photoSectionError: {
      borderColor: colors.danger,
      borderWidth: 1.5,
    },
    photoPlaceholder: {
      height: 240,
      backgroundColor: colors.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
    },
    photoPlaceholderEmoji: {
      fontSize: 44,
    },
    photoPlaceholderTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
    },
    photoPlaceholderSub: {
      fontSize: 13,
      color: colors.textSecondary,
      textAlign: 'center',
      paddingHorizontal: 30,
    },
    openCameraBtn: {
      marginTop: 6,
      backgroundColor: colors.accent,
      paddingHorizontal: 26,
      paddingVertical: 11,
      borderRadius: 50,
    },
    openCameraBtnText: {
      color: colors.white,
      fontSize: 14,
      fontWeight: '700',
    },
    photoPreview: {
      width: '100%',
      height: 240,
    },
    retakeBtn: {
      position: 'absolute',
      bottom: 54,
      right: 12,
      backgroundColor: 'rgba(0,0,0,0.6)',
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 13,
      paddingVertical: 7,
      borderRadius: 50,
      gap: 5,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.25)',
    },
    retakeBtnText: {
      color: '#FFFFFF',
      fontSize: 12,
      fontWeight: '700',
    },
    addressBar: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 13,
      paddingVertical: 10,
      backgroundColor: colors.accentDim,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      gap: 7,
      minHeight: 40,
    },
    addressBarText: {
      flex: 1,
      fontSize: 12,
      color: colors.accent,
      fontWeight: '500',
      lineHeight: 17,
    },
    addressBarLoading: {
      flex: 1,
      fontSize: 12,
      color: colors.textSecondary,
      fontStyle: 'italic',
    },
    photoErrorText: {
      fontSize: 12,
      color: colors.danger,
      marginHorizontal: 14,
      marginTop: 5,
    },
    formSection: {
      paddingHorizontal: 14,
      gap: 18,
      marginTop: 4,
    },
    fieldGroup: {
      gap: 5,
    },
    fieldLabel: {
      fontSize: 11,
      fontWeight: '800',
      color: colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.9,
    },
    fieldHint: {
      fontSize: 12,
      color: colors.textMuted,
    },
    input: {
      backgroundColor: colors.inputBg,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 15,
      color: colors.text,
    },
    inputFocused: {
      borderColor: colors.accent,
      borderWidth: 1.5,
    },
    inputError: {
      borderColor: colors.danger,
      borderWidth: 1.5,
    },
    textArea: {
      height: 110,
      textAlignVertical: 'top',
      paddingTop: 12,
    },
    fieldError: {
      fontSize: 12,
      color: colors.danger,
      marginTop: 2,
    },
    charRow: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
    },
    charCount: {
      fontSize: 11,
      color: colors.textMuted,
      marginTop: 3,
    },
    charCountWarn: {
      color: colors.danger,
    },
    divider: {
      height: 1,
      backgroundColor: colors.border,
    },
    infoBox: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
      backgroundColor: colors.surfaceElevated,
      borderRadius: 12,
      padding: 13,
      marginHorizontal: 14,
      marginTop: 6,
      borderWidth: 1,
      borderColor: colors.border,
    },
    infoBoxIcon: {
      fontSize: 14,
      marginTop: 1,
    },
    infoBoxText: {
      flex: 1,
      fontSize: 12,
      color: colors.textSecondary,
      lineHeight: 18,
    },
  });
