import { StyleSheet, Platform } from 'react-native';
import { ThemeColors } from '../../context/ThemeContext';

export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      paddingTop: Platform.OS === 'ios' ? 56 : 40,
      paddingBottom: 14,
      paddingHorizontal: 18,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.headerBg,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    headerLeft: {
      flex: 1,
    },
    headerTitle: {
      fontSize: 22,
      fontWeight: '800',
      color: colors.text,
      letterSpacing: -0.5,
    },
    headerSubtitle: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 2,
    },
    headerBadge: {
      marginTop: 4,
      alignSelf: 'flex-start',
      backgroundColor: colors.accentDim,
      borderRadius: 20,
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderWidth: 1,
      borderColor: colors.accent + '33',
    },
    headerBadgeText: {
      fontSize: 11,
      color: colors.accent,
      fontWeight: '600',
    },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    iconButton: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: colors.surfaceElevated,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    iconButtonText: {
      fontSize: 17,
    },
    addBtn: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
    },
    addBtnText: {
      color: colors.white,
      fontSize: 24,
      lineHeight: 26,
      fontWeight: '300',
      marginTop: -1,
    },
    listContent: {
      paddingTop: 10,
      paddingBottom: 100,
    },
    card: {
      marginHorizontal: 14,
      marginVertical: 7,
      borderRadius: 18,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: 'hidden',
      shadowColor: colors.cardShadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.07,
      shadowRadius: 8,
      elevation: 3,
    },
    cardImage: {
      width: '100%',
      height: 210,
      backgroundColor: colors.surfaceElevated,
    },
    cardBody: {
      padding: 14,
    },
    cardTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 6,
    },
    cardTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
      flex: 1,
      marginRight: 10,
      letterSpacing: -0.2,
    },
    removeBtn: {
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 20,
      backgroundColor: colors.dangerDim,
      borderWidth: 1,
      borderColor: colors.danger + '44',
    },
    removeBtnText: {
      color: colors.danger,
      fontSize: 12,
      fontWeight: '700',
    },
    cardDescription: {
      fontSize: 14,
      color: colors.textSecondary,
      lineHeight: 20,
      marginBottom: 10,
    },
    cardMeta: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 5,
    },
    cardPin: {
      fontSize: 12,
    },
    cardAddress: {
      fontSize: 12,
      color: colors.accent,
      fontWeight: '500',
      flex: 1,
    },
    cardDot: {
      fontSize: 10,
      color: colors.textMuted,
    },
    cardDate: {
      fontSize: 11,
      color: colors.textMuted,
    },
    emptyWrapper: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 40,
      paddingBottom: 60,
    },
    emptyEmoji: {
      fontSize: 60,
      marginBottom: 18,
    },
    emptyTitle: {
      fontSize: 22,
      fontWeight: '800',
      color: colors.text,
      marginBottom: 8,
      letterSpacing: -0.4,
    },
    emptyBody: {
      fontSize: 14,
      color: colors.textSecondary,
      textAlign: 'center',
      lineHeight: 22,
      marginBottom: 32,
    },
    emptyBtn: {
      backgroundColor: colors.accent,
      paddingHorizontal: 30,
      paddingVertical: 13,
      borderRadius: 50,
    },
    emptyBtnText: {
      color: colors.white,
      fontSize: 15,
      fontWeight: '700',
    },
    loadingWrapper: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
    },
    loadingText: {
      fontSize: 14,
      color: colors.textSecondary,
    },
  });
