import { StyleSheet, Platform, Dimensions } from 'react-native';
import { ThemeColors } from '../../context/ThemeContext';
const { height } = Dimensions.get('window');
export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },

    // ── Header ────────────────────────────────────────────────
    header: {
      paddingTop: Platform.OS === 'ios' ? 58 : 42,
      paddingBottom: 14,
      paddingHorizontal: 20,
      backgroundColor: colors.headerBg,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    headerLeft: { flex: 1 },
    appName: {
      fontSize: 28,
      fontWeight: '900',
      color: colors.text,
      letterSpacing: -1,
    },
    appNameAccent: { color: colors.accent },
    appTagline: {
      fontSize: 11,
      color: colors.textMuted,
      marginTop: 2,
      letterSpacing: 0.3,
    },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    iconBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 4,
      elevation: 2,
    },

    // ── Search bar ────────────────────────────────────────────
    searchContainer: {
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 10,
      backgroundColor: colors.headerBg,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    searchWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surfaceElevated,
      borderRadius: 14,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      paddingHorizontal: 12,
      height: 44,
      gap: 8,
    },
    searchWrapActive: {
      borderColor: colors.accent,
      backgroundColor: colors.accentDim,
    },
    searchInput: {
      flex: 1,
      fontSize: 15,
      color: colors.text,
      paddingVertical: 0,
    },
    searchClearBtn: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: colors.textMuted + '55',
      alignItems: 'center',
      justifyContent: 'center',
    },

    // ── FAB ───────────────────────────────────────────────────
    fab: {
      position: 'absolute',
      bottom: Platform.OS === 'ios' ? 40 : 28,
      right: 20,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      backgroundColor: colors.accent,
      paddingHorizontal: 22,
      paddingVertical: 15,
      borderRadius: 50,
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.4,
      shadowRadius: 14,
      elevation: 8,
    },
    fabText: {
      color: colors.white,
      fontSize: 15,
      fontWeight: '800',
      letterSpacing: 0.1,
    },

    // ── List ──────────────────────────────────────────────────
    listContent: {
      paddingTop: 16,
      paddingHorizontal: 16,
      paddingBottom: 110,
      gap: 14,
    },

    // ── Card ──────────────────────────────────────────────────
    card: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      overflow: 'hidden',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 4,
    },
    cardImageWrap: {
      width: '100%',
      height: 185,
      backgroundColor: colors.surfaceElevated,
    },
    cardImage: { width: '100%', height: '100%' },
    cardImagePlaceholder: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      backgroundColor: colors.surfaceElevated,
    },
    cardImagePlaceholderText: {
      fontSize: 11,
      color: colors.textMuted,
      letterSpacing: 1,
      fontWeight: '600',
    },
    cardBody: {
      paddingHorizontal: 16,
      paddingTop: 13,
      paddingBottom: 13,
    },
    cardTopRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      marginBottom: 5,
    },
    cardTitle: {
      fontSize: 16,
      fontWeight: '800',
      color: colors.text,
      flex: 1,
      letterSpacing: -0.4,
      lineHeight: 21,
      marginRight: 8,
    },
    optionsBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: -2,
    },
    cardDescription: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 19,
      marginBottom: 10,
    },
    cardFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginTop: 2,
    },
    cardAddress: {
      fontSize: 12,
      color: colors.accent,
      fontWeight: '600',
      flex: 1,
    },
    cardDate: {
      fontSize: 11,
      color: colors.textMuted,
      fontWeight: '500',
    },

    // ── Empty state (shared base) ──────────────────────────────
    emptyWrapper: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 32,
      paddingBottom: 80,
    },
    emptyIconWrap: {
      width: 88,
      height: 88,
      borderRadius: 44,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 24,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 3,
    },
    emptyTitle: {
      fontSize: 22,
      fontWeight: '900',
      color: colors.text,
      marginBottom: 10,
      letterSpacing: -0.5,
      textAlign: 'center',
    },
    emptyBody: {
      fontSize: 14,
      color: colors.textSecondary,
      textAlign: 'center',
      lineHeight: 22,
      marginBottom: 32,
    },
    emptyBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.accent,
      paddingHorizontal: 28,
      paddingVertical: 15,
      borderRadius: 50,
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.35,
      shadowRadius: 10,
      elevation: 5,
    },
    emptyBtnText: {
      color: colors.white,
      fontSize: 15,
      fontWeight: '800',
      letterSpacing: 0.1,
    },

    // ── No results (search) — same structure as emptyWrapper ──
    clearSearchBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 28,
      paddingVertical: 15,
      borderRadius: 50,
      borderWidth: 1.5,
      borderColor: colors.accent,
      backgroundColor: colors.accentDim,
    },
    clearSearchBtnText: {
      color: colors.accent,
      fontSize: 15,
      fontWeight: '800',
      letterSpacing: 0.1,
    },

    loadingWrapper: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 14,
    },
    loadingText: {
      fontSize: 14,
      color: colors.textSecondary,
    },

    // ── Options bottom sheet ───────────────────────────────────
    optionsOverlay: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: 'flex-end',
    },
    optionsSheet: {
      backgroundColor: colors.modalBg,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingBottom: Platform.OS === 'ios' ? 36 : 24,
    },
    optionsHandle: {
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.border,
      alignSelf: 'center',
      marginTop: 14,
      marginBottom: 6,
    },
    optionsTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.textMuted,
      paddingHorizontal: 20,
      paddingBottom: 12,
      paddingTop: 4,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    optionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      paddingHorizontal: 20,
      paddingVertical: 15,
    },
    optionRowBorder: {
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    optionIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 13,
      alignItems: 'center',
      justifyContent: 'center',
    },
    optionText: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.text,
    },
    optionTextDanger: { color: colors.danger },
    optionCancelRow: {
      marginHorizontal: 16,
      marginTop: 8,
      backgroundColor: colors.surfaceElevated,
      borderRadius: 16,
      alignItems: 'center',
      paddingVertical: 15,
    },
    optionCancelText: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textSecondary,
    },

    // ── Detail modal ───────────────────────────────────────────
    detailOverlay: {
      flex: 1,
      backgroundColor: colors.overlay,
      flexDirection: 'column',
      justifyContent: 'flex-end',
    },
    detailBackdrop: { flex: 1 },
    detailSheet: {
      height: height * 0.92,
      backgroundColor: colors.modalBg,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      overflow: 'hidden',
    },
    detailScroll: { flex: 1 },
    detailScrollContent: {
      paddingBottom: Platform.OS === 'ios' ? 80 : 60,
    },
    detailImageWrap: {
      width: '100%',
      height: 300,
      backgroundColor: colors.surfaceElevated,
    },
    detailImageAbsoluteBar: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      flexDirection: 'row',
      justifyContent: 'flex-end',
      paddingHorizontal: 16,
      paddingTop: 16,
    },
    detailCloseBtn: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: 'rgba(0,0,0,0.45)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    detailImage: { width: '100%', height: '100%' },
    detailImagePlaceholder: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    detailImagePlaceholderText: {
      fontSize: 12,
      color: colors.textMuted,
      letterSpacing: 1,
    },
    detailBody: {
      paddingHorizontal: 20,
      paddingTop: 22,
    },
    detailTitle: {
      fontSize: 24,
      fontWeight: '900',
      color: colors.text,
      letterSpacing: -0.6,
      marginBottom: 8,
      lineHeight: 30,
    },
    detailDescription: {
      fontSize: 15,
      color: colors.textSecondary,
      lineHeight: 23,
      marginBottom: 22,
    },
    detailDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.border,
      marginBottom: 18,
    },
    detailMetaCard: {
      backgroundColor: colors.surfaceElevated,
      borderRadius: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      overflow: 'hidden',
      marginBottom: 20,
    },
    detailMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 14,
      paddingVertical: 14,
      gap: 12,
    },
    detailMetaRowBorder: {
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    detailMetaIconWrap: {
      width: 36,
      height: 36,
      borderRadius: 11,
      backgroundColor: colors.accentDim,
      alignItems: 'center',
      justifyContent: 'center',
    },
    detailMetaContent: { flex: 1 },
    detailMetaLabel: {
      fontSize: 10,
      fontWeight: '700',
      color: colors.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.9,
      marginBottom: 3,
    },
    detailMetaValue: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
      lineHeight: 19,
    },
    detailMetaAccent: { color: colors.accent },
    detailActionRow: {
      flexDirection: 'row',
      gap: 10,
    },
    detailEditBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
      paddingVertical: 15,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.accent + '50',
      backgroundColor: colors.accentDim,
    },
    detailEditBtnText: {
      color: colors.accent,
      fontSize: 14,
      fontWeight: '700',
    },
    detailRemoveBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
      paddingVertical: 15,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.danger + '40',
      backgroundColor: colors.dangerDim,
    },
    detailRemoveBtnText: {
      color: colors.danger,
      fontSize: 14,
      fontWeight: '700',
    },
  });