import { StyleSheet, Platform, Dimensions } from 'react-native';
import { ThemeColors } from '../../context/ThemeContext';

const { width, height } = Dimensions.get('window');

export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },

    header: {
      paddingTop: Platform.OS === 'ios' ? 58 : 42,
      paddingBottom: 16,
      paddingHorizontal: 20,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
      backgroundColor: colors.headerBg,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    headerLeft: {
      flex: 1,
    },
    appName: {
      fontSize: 28,
      fontWeight: '900',
      color: colors.text,
      letterSpacing: -1.2,
    },
    appNameAccent: {
      color: colors.accent,
    },
    appTagline: {
      fontSize: 12,
      color: colors.textMuted,
      marginTop: 1,
      letterSpacing: 0.2,
    },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    iconBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.surfaceElevated,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    addBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.accent,
      paddingHorizontal: 16,
      paddingVertical: 9,
      borderRadius: 50,
    },
    addBtnText: {
      color: colors.white,
      fontSize: 14,
      fontWeight: '700',
      letterSpacing: 0.1,
    },

    listContent: {
      paddingTop: 12,
      paddingHorizontal: 14,
      paddingBottom: 100,
      gap: 12,
    },

    card: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      overflow: 'hidden',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      shadowColor: colors.cardShadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 3,
    },
    cardImageWrap: {
      width: '100%',
      height: 200,
      backgroundColor: colors.surfaceElevated,
    },
    cardImage: {
      width: '100%',
      height: '100%',
    },
    cardImagePlaceholder: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    cardImagePlaceholderText: {
      fontSize: 12,
      color: colors.textMuted,
      letterSpacing: 1,
      fontWeight: '600',
    },

    cardBody: {
      padding: 14,
    },
    cardTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 6,
    },
    cardTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
      flex: 1,
      marginRight: 10,
      letterSpacing: -0.3,
      lineHeight: 22,
    },
    removeBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.dangerDim,
      borderWidth: 1,
      borderColor: colors.danger + '44',
      alignItems: 'center',
      justifyContent: 'center',
    },
    cardDescription: {
      fontSize: 13,
      color: colors.textSecondary,
      lineHeight: 19,
      marginBottom: 10,
    },
    cardFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    cardAddressWrap: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    cardAddress: {
      fontSize: 12,
      color: colors.accent,
      fontWeight: '500',
      flex: 1,
    },
    cardDateWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 3,
    },
    cardDate: {
      fontSize: 11,
      color: colors.textMuted,
    },
    cardDivider: {
      width: 3,
      height: 3,
      borderRadius: 2,
      backgroundColor: colors.textMuted,
      marginHorizontal: 2,
    },

    emptyWrapper: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 48,
      paddingBottom: 80,
    },
    emptyIconWrap: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: colors.surfaceElevated,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 20,
    },
    emptyTitle: {
      fontSize: 20,
      fontWeight: '800',
      color: colors.text,
      marginBottom: 8,
      letterSpacing: -0.4,
      textAlign: 'center',
    },
    emptyBody: {
      fontSize: 14,
      color: colors.textSecondary,
      textAlign: 'center',
      lineHeight: 21,
      marginBottom: 28,
    },
    emptyBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      backgroundColor: colors.accent,
      paddingHorizontal: 24,
      paddingVertical: 13,
      borderRadius: 50,
    },
    emptyBtnText: {
      color: colors.white,
      fontSize: 14,
      fontWeight: '700',
    },

    loadingWrapper: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 14,
    },
    loadingText: {
      fontSize: 14,
      color: colors.textSecondary,
    },

    modalOverlay: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: 'flex-end',
    },
    modalSheet: {
      backgroundColor: colors.modalBg,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      maxHeight: height * 0.9,
      overflow: 'hidden',
    },
    modalHandle: {
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.border,
      alignSelf: 'center',
      marginTop: 12,
      marginBottom: 2,
    },
    modalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingVertical: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    modalHeaderTitle: {
      fontSize: 16,
      fontWeight: '800',
      color: colors.text,
      letterSpacing: -0.3,
    },
    modalCloseBtn: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: colors.surfaceElevated,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalScrollContent: {
      paddingBottom: 48,
    },
    modalImageWrap: {
      width: '100%',
      height: 280,
      backgroundColor: colors.surfaceElevated,
    },
    modalImage: {
      width: '100%',
      height: '100%',
    },
    modalImagePlaceholder: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    modalImagePlaceholderText: {
      fontSize: 13,
      color: colors.textMuted,
      letterSpacing: 1,
    },
    modalBody: {
      padding: 20,
    },
    modalTitle: {
      fontSize: 24,
      fontWeight: '800',
      color: colors.text,
      letterSpacing: -0.6,
      marginBottom: 8,
      lineHeight: 30,
    },
    modalDescription: {
      fontSize: 15,
      color: colors.textSecondary,
      lineHeight: 23,
      marginBottom: 20,
    },
    modalDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.border,
      marginBottom: 18,
    },
    modalMetaCard: {
      backgroundColor: colors.surfaceElevated,
      borderRadius: 14,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      overflow: 'hidden',
      marginBottom: 16,
    },
    modalMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 13,
      gap: 12,
    },
    modalMetaRowBorder: {
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    modalMetaIconWrap: {
      width: 34,
      height: 34,
      borderRadius: 10,
      backgroundColor: colors.accentDim,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalMetaContent: {
      flex: 1,
    },
    modalMetaLabel: {
      fontSize: 10,
      fontWeight: '700',
      color: colors.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginBottom: 2,
    },
    modalMetaValue: {
      fontSize: 14,
      color: colors.text,
      lineHeight: 19,
    },
    modalMetaAccent: {
      color: colors.accent,
    },
    modalRemoveBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      marginHorizontal: 20,
      marginTop: 4,
      paddingVertical: 14,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.danger + '55',
      backgroundColor: colors.dangerDim,
    },
    modalRemoveBtnText: {
      color: colors.danger,
      fontSize: 14,
      fontWeight: '700',
    },
  });